# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Skip Intro Plex
version: "1.2.0"
slug: example
description: Skip Intro - Plex add-on
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
